apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: sparkport
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: terminalport
  selector:
    app: spark-app
